---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.6 comprend un certain nombre de nouvelles fonctionnalités et améliorations. 
---
= Nouveautés de Cloud Volumes ONTAP 9.6
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.6 comprend un certain nombre de nouvelles fonctionnalités et améliorations.

D'autres fonctionnalités et améliorations sont également introduites dans les dernières versions de Cloud Manager. Voir la https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Notes de version de Cloud Manager"^] pour plus d'informations.



== 9.6 P8 (2 juin 2020)

La version 9.6 P8 patch pour Cloud Volumes ONTAP est désormais disponible via Cloud Manager 3.8 et versions ultérieures. Cloud Manager vous invite à mettre à niveau vos systèmes existants vers cette version de correctif. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P8["Consultez la liste des bugs corrigés dans le correctif P8"^] (Identifiant du site du support NetApp requis).



== 9.6 P7 (8 avril 2020)

La version 9.6 P7 du correctif pour Cloud Volumes ONTAP est désormais disponible sur Cloud Manager 3.8 et versions ultérieures. Cloud Manager vous invite à mettre à niveau vos systèmes existants vers cette version de correctif. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P7["Consultez la liste des bugs corrigés dans le patch P7"^] (Identifiant du site du support NetApp requis).



== 9.6 P6 (6 mars 2020)

La version 9.6 P6 patch pour Cloud Volumes ONTAP est désormais disponible via Cloud Manager 3.8 et versions ultérieures. Cloud Manager vous invite à mettre à niveau vos systèmes existants vers cette version de correctif. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P6["Consultez la liste des bugs corrigés dans le correctif P6"^] (Identifiant du site du support NetApp requis).



== Mises à jour AWS (16 février 2020)

Nous avons introduit la prise en charge de nouvelles instances EC2 et une modification du nombre de disques de données pris en charge.



=== Prise en charge des nouvelles instances

Quelques nouveaux types d'instances EC2 sont désormais pris en charge avec Cloud Volumes ONTAP 9.6 avec une licence Premium ou BYOL :

* c5.9xlarge
* c5d.18xlarge ^1,2^
* m5d.mcd ^1,2^


^1^ ces types d'instances incluent le stockage NVMe local, que Cloud Volumes ONTAP utilise comme _Flash cache_. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-flash-cache.html["En savoir plus >>"^].

^2^ ces types d'instance sont pris en charge par 9.6 P3 ou ultérieur.

https://aws.amazon.com/ec2/instance-types/["En savoir plus sur ces types d'instances EC2"^].

link:reference-configs-aws.html["En savoir plus sur les 9.6 configurations prises en charge dans AWS"].



=== Disques de données pris en charge

Un disque de données de moins est désormais pris en charge pour les instances c5, m5 et r5. Pour les systèmes à un seul nœud, 22 disques de données sont pris en charge. Pour les paires haute disponibilité, 19 disques de données sont pris en charge par nœud.

link:reference-limits-aws.html["En savoir plus sur les limites de stockage dans AWS"].



== Prise en charge de DS15_v2 dans Azure (12 février 2020)

Cloud Volumes ONTAP est désormais pris en charge avec le type de machine virtuelle DS15_v2 dans Azure, aussi bien sur des systèmes à un seul nœud que sur des paires haute disponibilité.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["En savoir plus sur la gamme DSv2"^].

link:reference-configs-azure.html["En savoir plus sur les 9.6 configurations prises en charge dans Azure"].



== 9.6 P5 (26 déc. 2019)

La version 9.6 du correctif P5 pour Cloud Volumes ONTAP est désormais disponible via Cloud Manager. Cloud Manager vous invite à mettre à niveau vos systèmes existants vers cette version de correctif. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P5["Afficher la liste des bugs corrigés dans le patch P5"^] (Identifiant du site du support NetApp requis).



== 9.6 P4 (14 nov 2019)

La version 9.6 P4 du correctif pour Cloud Volumes ONTAP est désormais disponible via Cloud Manager. Cloud Manager vous invite à mettre à niveau vos systèmes existants vers cette version de correctif. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P4["Consultez la liste des bugs corrigés dans le patch P4"^] (Identifiant du site du support NetApp requis).



== 9.6 P3 (23 oct 2019)

La version 9.6 P3 du correctif est Cloud Volumes ONTAP désormais disponible via Cloud Manager. Cloud Manager vous invite à mettre à niveau les systèmes existants vers cette version de correctif. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P3["Consultez la liste des bugs corrigés dans le patch P3"^] (Identifiant du site du support NetApp requis).

Outre les correctifs de bogues, cette version apporte également les avantages suivants :

* Prise en charge du type d'instance c5.18XLarge dans AWS.
* Augmentation de la taille maximale de l'agrégat sur des systèmes à un seul nœud dans Azure : 352 To de capacité brute sont désormais pris en charge.
+
Auparavant, la taille maximale de l'agrégat pour un système à un seul nœud était de 200 To.





== Abonnements avec paiement à l'utilisation sur Google Cloud Marketplace (6 octobre 2019)

Vous pouvez payer Cloud Volumes ONTAP selon votre utilisation en vous abonnant à Cloud Volumes ONTAP sur le marché Google Cloud Platform.

https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?q=NetApp&id=8108721b-10e5-48be-88ed-387031dae492["Google Cloud Platform Marketplace : Cloud Manager pour Cloud Volumes ONTAP"^]



== Disponibilité générale de Cloud Volumes ONTAP dans Google Cloud (3 septembre 2019)

Cloud Volumes ONTAP est maintenant disponible dans Google Cloud Platform (Google Cloud) lorsque vous apportez votre propre licence (BYOL). Une offre de paiement à l'utilisation est également disponible. La promotion offre des licences gratuites pour un nombre illimité de systèmes et expirera à la fin de septembre 2019.

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Découvrez comment vous lancer dans Google Cloud"^]
* link:reference-configs-gcp.html["Affichez les configurations prises en charge"]




== 9.6 P2 (29 août 2019)

La version 9.6 du correctif P2 pour Cloud Volumes ONTAP est désormais disponible via Cloud Manager. Cloud Manager vous invite à mettre à niveau vos systèmes 9.5 et 9.6 existants vers cette version de correctif. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P2["Consultez la liste des bugs corrigés dans le patch P2"^] (Identifiant du site du support NetApp requis).



== 9.6 GA (15 juillet 2019)

La version GA de Cloud Volumes ONTAP 9.6 est désormais disponible. La version GA inclut des correctifs. Cloud Manager vous invitera à mettre à niveau vos systèmes existants vers cette version.


NOTE: Cloud Volumes ONTAP reste en préversion privée dans Google Cloud Platform.



== 9.6 RC1 (16 juin 2019)

Cloud Volumes ONTAP 9.6 RC1 est disponible dans AWS, Azure et désormais dans Google Cloud Platform. Cette version inclut les fonctionnalités suivantes.

*  preview of Cloud Volumes ONTAP in Google Cloud Platform
*  tiering with HA pairs in Azure
*  for FlexCache volumes
*  ONTAP changes




=== Préversion privée de Cloud Volumes ONTAP dans Google Cloud Platform

Une présentation privée de Cloud Volumes ONTAP dans Google Cloud Platform est disponible. Comme les autres fournisseurs cloud, Cloud Volumes ONTAP pour Google Cloud Platform vous permet de réduire les coûts, d'améliorer les performances et d'augmenter la disponibilité.

Cloud Volumes ONTAP est disponible dans Google Cloud sous forme de système à nœud unique et prend en charge le Tiering des données vers le stockage objet.

Pour rejoindre la présentation privée, envoyez une demande à l'adresse ng-Cloud-Volume-ONTAP-preview@netapp.com.



=== Tiering des données avec paires haute disponibilité dans Azure

Le Tiering des données est désormais pris en charge avec les paires HA Cloud Volumes ONTAP dans Microsoft Azure. Le Tiering des données permet le Tiering automatisé des données inactives vers le stockage Blob à faible coût.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html["Découvrez comment configurer le Tiering des données dans Cloud Manager"^].



=== Prise en charge des volumes FlexCache

Un volume FlexCache est un volume de stockage qui met en cache les données lues par NFS à partir d'un volume d'origine (ou source). Les lectures suivantes des données mises en cache permettent un accès plus rapide à ces données.

Les volumes FlexCache peuvent être utilisés pour accélérer l'accès aux données ou pour décharger le trafic des volumes fortement sollicités. Les volumes FlexCache contribuent à améliorer les performances, en particulier lorsque les clients doivent accéder de façon répétée aux mêmes données, car elles peuvent être servies directement sans avoir à accéder au volume d'origine. Les volumes FlexCache fonctionnent parfaitement pour les charges de travail système intensives en lecture.

Cloud Manager n'assure pas la gestion des volumes FlexCache pour le moment, mais vous pouvez utiliser l'interface de ligne de commande ONTAP ou ONTAP System Manager pour créer et gérer des volumes FlexCache :

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["Guide de puissance des volumes FlexCache pour un accès plus rapide aux données"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["Création de volumes FlexCache dans System Manager"^]


À partir de la version 3.7.2, Cloud Manager génère une licence FlexCache pour tous les nouveaux systèmes Cloud Volumes ONTAP. La licence inclut une limite d'utilisation de 500 Gio.



=== Autres modifications apportées à ONTAP

ONTAP 9.6 comprend d'autres modifications qui pourraient intéresser les utilisateurs d'Cloud Volumes ONTAP :

* La réplication SnapMirror prend désormais en charge le chiffrement TLS 1.2 pour les communications à la volée
* Le Tiering des données (FabricPool) a été amélioré :
+
** Prise en charge du déplacement de volumes sans avoir à redéfinir le Tiering des données inactives
** Prise en charge de la reprise d'activité des SVM




Pour plus d'informations sur la version 9.6, consultez le https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de version de ONTAP 9"^].



== Notes de mise à niveau

* La mise à niveau d'Cloud Volumes ONTAP doit être effectuée depuis Cloud Manager. Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l'aide de System Manager ou de l'interface de ligne de commandes. Cela peut affecter la stabilité du système.
* Vous pouvez effectuer la mise à niveau vers Cloud Volumes ONTAP 9.6 à partir de la version 9.5.
* La mise à niveau d'un système à un nœud unique permet de mettre le système hors ligne pendant 25 minutes au cours desquelles les E/S sont interrompues.
* La mise à niveau d'une paire haute disponibilité s'effectue sans interruption et les E/S sont continues. Au cours de ce processus de mise à niveau sans interruption, chaque nœud est mis à niveau en tandem afin de continuer à traiter les E/S aux clients.

