---
sidebar: sidebar 
permalink: reference-limits-azure.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks 
summary: Cloud Volumes ONTAP présente des limites de configuration du stockage dans Azure pour des opérations fiables. Pour des performances optimales, ne configurez pas votre système aux valeurs maximales. 
---
= Limites de stockage dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP présente des limites de configuration du stockage pour assurer des opérations fiables. Pour des performances optimales, ne configurez pas votre système aux valeurs maximales.



== Capacité système maximale par licence

La capacité système maximale d'un système Cloud Volumes ONTAP est déterminée par sa licence. La capacité système maximale inclut le stockage sur disque et le stockage objet utilisé pour le Tiering des données. NetApp ne prend pas en charge le dépassement de cette limite.

[cols="25,75"]
|===
| Licence | Capacité système maximale (disques + stockage objet) 


| Découvrir | 2 Tio (le Tiering des données n'est pas pris en charge sur Explore) 


| Standard | 10 To 


| Premium | 368 To 


| BYOL | 368 Tio par licence 
|===
La limite de capacité s'adresse à l'ensemble de la paire haute disponibilité. Il n'est pas par nœud. Par exemple, si vous utilisez la licence Premium, vous pouvez disposer d'une capacité pouvant atteindre 368 Tio entre les deux nœuds.



== Limite des disques et du Tiering en fonction de la taille des machines virtuelles

Les limites de disque ci-dessous sont spécifiques aux disques qui contiennent des données utilisateur. Les limites n'incluent pas le disque d'amorçage et le disque racine. Les tableaux ci-dessous présentent la capacité maximale du système par taille de machine virtuelle avec des disques ou seuls, ainsi que le Tiering des données inactives vers le stockage objet.

La taille des machines virtuelles est limitée pour les licences Premium et BYOL. En effet, les limites de disque ne peuvent être atteintes avec les licences Explore ou Standard en raison des limites de capacité du système.

* Les systèmes à un seul nœud peuvent utiliser des disques gérés HDD standard, des disques gérés SSD standard et des disques gérés SSD premium, avec jusqu'à 32 To par disque. Le nombre de disques pris en charge varie en fonction de la taille des machines virtuelles.
* Les systèmes HAUTE DISPONIBILITÉ utilisent des objets blob de pages Premium en tant que disques, avec jusqu'à 8 Tio par page. Le nombre de disques pris en charge varie en fonction de la taille des machines virtuelles.




=== Un seul nœud avec une licence Premium

[cols="14,20,31,33"]
|===
| Taille des machines virtuelles | Nombre maximal de disques par nœud | Capacité système maximale avec des disques seuls | Capacité système maximale avec disques et Tiering des données 


| DS5_v2 | 63 | 368 To | 368 To 


| DS14_v2 | 63 | 368 To | 368 To 


| DS15_v2 | 63 | 368 To | 368 To 
|===


=== Un seul nœud avec une ou plusieurs licences BYOL


NOTE: Pour certains types de VM, vous aurez besoin de plusieurs licences BYOL pour atteindre la capacité maximale indiquée ci-dessous. Par exemple, vous aurez besoin de 6 licences BYOL pour atteindre 2 Pio avec DS5_v2.

[cols="10,18,18,18,18,18"]
|===
| Taille des machines virtuelles | Nombre maximal de disques par nœud 2+| Capacité système max. Avec une licence 2+| Capacité système max. Avec plusieurs licences 


2+|  | *Disques seuls* | *Disques + hiérarchisation des données* | *Disques seuls* | *Disques + hiérarchisation des données* 


| DS3_v2 | 15 | 368 To | 368 To | 480 To | 368 Tio x chaque licence 


| DS4_v2 | 31 | 368 To | 368 To | 896 To | 368 Tio x chaque licence 


| DS5_v2 | 63 | 368 To | 368 To | 896 To | 368 Tio x chaque licence 


| DS13_v2 | 31 | 368 To | 368 To | 896 To | 368 Tio x chaque licence 


| DS14_v2 | 63 | 368 To | 368 To | 896 To | 368 Tio x chaque licence 


| DS15_v2 | 63 | 368 To | 368 To | 896 To | 368 Tio x chaque licence 
|===


=== Paires HA avec une licence Premium

[cols="14,20,31,33"]
|===
| Taille des machines virtuelles | Disques MAX Data pour une paire haute disponibilité | Capacité système maximale avec des disques seuls | Capacité système maximale avec disques et Tiering des données 


| DS5_v2 | 63 | 368 To | 368 To 


| DS14_v2 | 63 | 368 To | 368 To 


| DS15_v2 | 63 | 368 To | 368 To 
|===


=== Paires HAUTE DISPONIBILITÉ avec une ou plusieurs licences BYOL

[cols="10,18,18,18,18,18"]
|===
| Taille des machines virtuelles | Disques MAX Data pour une paire haute disponibilité 2+| Capacité système max. Avec une licence 2+| Capacité système max. Avec plusieurs licences 


2+|  | *Disques seuls* | *Disques + hiérarchisation des données* | *Disques seuls* | *Disques + hiérarchisation des données* 


| DS4_v2 | 31 | 368 To | 368 To | 248 To | 368 Tio x chaque licence 


| DS5_v2 | 63 | 368 To | 368 To | 504 To | 368 Tio x chaque licence 


| DS13_v2 | 31 | 368 To | 368 To | 248 To | 368 Tio x chaque licence 


| DS14_v2 | 63 | 368 To | 368 To | 504 To | 368 Tio x chaque licence 


| DS15_v2 | 63 | 368 To | 368 To | 504 To | 368 Tio x chaque licence 
|===


== Restrictions agrégées

Cloud Volumes ONTAP utilise le stockage Azure comme disques et les regroupe dans des _agrégats_. Les agrégats fournissent du stockage aux volumes.

[cols="2*"]
|===
| Paramètre | Limite 


| Nombre maximal d'agrégats | Identique à la limite du disque 


| Taille maximale des agrégats | 352 Tio de capacité brute pour un seul nœud ^1,^ ^2^ 96 Tio de capacité brute pour les paires haute disponibilité ^1^ 


| Disques par agrégat | 1-12 ^3^ 


| Nombre maximal de groupes RAID par agrégat | 1 
|===
Remarques :

. La limite de capacité de l'agrégat dépend des disques qui composent l'agrégat. La limite n'inclut pas le stockage objet utilisé pour le Tiering des données.
. La limite de 352 Tio est prise en charge à partir de la version 9.6 P3. Les versions antérieures à 9.6 P3 prennent en charge jusqu'à 200 Tio de capacité brute dans un agrégat sur un système à un seul nœud.
. Tous les disques qui composent un agrégat doivent être de la même taille.




== Limites de stockage logique

[cols="22,22,56"]
|===
| Stockage logique | Paramètre | Limite 


| *Machines virtuelles de stockage (SVM)* | Nombre maximal pour Cloud Volumes ONTAP (paire HA ou nœud unique) | Un SVM de service des données et un SVM de destination utilisés pour la reprise après incident. Vous pouvez activer le SVM de destination pour l'accès aux données en cas de panne sur le SVM source. ^1^ le SVM qui transmet les données couvre l'ensemble du système Cloud Volumes ONTAP (paire HA ou nœud unique). 


.2+| *Fichiers* | Taille maximale | 16 To 


| Maximum par volume | Selon la taille du volume, jusqu'à 2 milliards 


| *Volumes FlexClone* | Profondeur de clone hiérarchique ^2^ | 499 


.3+| *Volumes FlexVol* | Maximale par nœud | 500 


| Taille minimale | 20 MO 


| Taille maximale | 100 To 


| *Qtrees* | Maximum par volume FlexVol | 4,995 


| *Copies snapshot* | Maximum par volume FlexVol | 1,023 
|===
Remarques :

. Cloud Manager ne prend pas en charge la configuration ou l'orchestration de la reprise après incident SVM. Il ne prend pas non plus en charge les tâches relatives au stockage sur une SVM supplémentaire. Vous devez utiliser System Manager ou l'interface de ligne de commande pour la reprise après incident SVM.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guide de préparation rapide pour la reprise après incident du SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guide de reprise après incident de SVM Express"^]


. La profondeur de clone hiérarchique correspond à la profondeur maximale d'une hiérarchie imbriquée de volumes FlexClone qui peut être créée à partir d'un seul volume FlexVol.




== Limites de stockage iSCSI

[cols="3*"]
|===
| Stockage iSCSI | Paramètre | Limite 


.4+| *LUN* | Maximale par nœud | 1,024 


| Nombre maximal de mappages de LUN | 1,024 


| Taille maximale | 16 To 


| Maximum par volume | 512 


| *igroups* | Maximale par nœud | 256 


.2+| *Initiateurs* | Maximale par nœud | 512 


| Maximum par groupe initiateur | 128 


| *Sessions iSCSI* | Maximale par nœud | 1,024 


.2+| *Lifs* | Maximum par port | 32 


| Maximum par ensemble de ports | 32 


| *Porsets* | Maximale par nœud | 256 
|===