---
sidebar: sidebar 
permalink: reference-configs-azure.html 
keywords: vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, disks, sizes 
summary: Cloud Volumes ONTAP est disponible dans Azure en configurations PAYGO et BYOL. Vous avez le choix entre Explorer, Standard ou Premium. 
---
= Configurations prises en charge dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deux options de tarification sont disponibles pour Cloud Volumes ONTAP dans Azure : le paiement à l'utilisation ou le modèle BYOL (où vous apportez votre propre licence). Le paiement basé sur l'utilisation vous permet de choisir parmi trois configurations : explore, Standard ou Premium.



== Configurations prises en charge par licence

Cloud Volumes ONTAP est disponible dans Azure en tant que système à un seul nœud et en tant que paire de nœuds haute disponibilité pour la tolérance aux pannes et la continuité de l'activité.

La mise à niveau d'un système à un seul nœud vers une paire haute disponibilité n'est pas prise en charge. Si vous souhaitez passer d'un système à un seul nœud à une paire haute disponibilité, vous devez déployer un nouveau système et répliquer les données du système existant vers le nouveau.



=== Systèmes à un seul nœud

Lors du déploiement de Cloud Volumes ONTAP en tant que système à un seul nœud dans Azure, vous pouvez choisir l'une des configurations suivantes :

[cols="h,d,d,d,d"]
|===
|  | Découvrir | Standard | Premium | BYOL 


| Types de machines virtuelles pris en charge | DS3_v2  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2
* DS15_v2

 a| 
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2
* DS15_v2




| Types de disque pris en charge ^1^ 4+| Disques gérés HDD standard, disques gérés SSD standard et disques gérés SSD premium 


| Tiering des données inactives vers le stockage Blob | Non pris en charge 3+| Pris en charge 


| Capacité système maximale (disques + stockage objet) | 2 To | 10 To | 368 To | 368 Tio par licence 
|===
Remarques :

. Les performances améliorées en écriture sont activées lors de l'utilisation de disques SSD, mais pas avec le type de machine virtuelle DS3_v2.
. Pour la prise en charge par région Azure, consultez la section https://cloud.netapp.com/cloud-volumes-global-regions["Régions Cloud volumes Global"^].




=== Paires HA

Lors du déploiement de Cloud Volumes ONTAP en tant que paire HA dans Azure, vous pouvez choisir l'une des configurations suivantes :

[cols="h,d,d,d,d"]
|===
|  | Découvrir | Standard | Premium | BYOL 


| Types de machines virtuelles pris en charge | Non pris en charge  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2
* DS15_v2

 a| 
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2
* DS15_v2




| Types de disques pris en charge | Non pris en charge 3+| Blobs de page Premium 


| Tiering des données inactives vers du stockage Blob ^2^ | Non pris en charge 3+| Pris en charge 


| Capacité système maximale (disques + stockage objet) | Non pris en charge | 10 To | 368 To | 368 Tio par licence 
|===
Remarques :

. Pour la prise en charge par région Azure, consultez la section https://cloud.netapp.com/cloud-volumes-global-regions["Régions Cloud volumes Global"^].




== Tailles de disque prises en charge

Dans Azure, un agrégat peut contenir jusqu'à 12 disques de même type et de même taille.



=== Systèmes à un seul nœud

Les systèmes à un seul nœud utilisent des disques gérés Azure. Les tailles de disque suivantes sont prises en charge :

[cols="3*"]
|===
| SSD premium | SSD standard | Disque dur standard 


 a| 
* 500 Gio
* 1 To
* 2 To
* 4 To
* 8 To
* 16 To
* 32 To

 a| 
* 100 Gio
* 500 Gio
* 1 To
* 2 To
* 4 To
* 8 To
* 16 To
* 32 To

 a| 
* 100 Gio
* 500 Gio
* 1 To
* 2 To
* 4 To
* 8 To
* 16 To
* 32 To


|===


=== Paires HA

Les paires HAUTE DISPONIBILITÉ utilisent des objets blob de pages Premium. Les tailles de disque suivantes sont prises en charge :

* 500 Gio
* 1 To
* 2 To
* 4 To
* 8 To

